sudo: false

before_script:
 - wget https://github.com/gohugoio/hugo/releases/download/v0.24.1/hugo_0.24.1_Linux-64bit.tar.gz
 - tar -zxvf hugo_0.24.1_Linux-64bit.tar.gz
 - npm install

script:
 - npm run build
 - ./hugo

deploy:
  provider: surge
  project: ./public/
  domain: planette.surge.sh
  skip_cleanup: true
